export const SPALTEN_FELDER = {
  produkt: [
    'produkt_kategorie',
    'produkt_hersteller',
    'produkt_name_modell',
    'produkt_produktlinie_serie',
    'produkt_code_id',
    'produkt_anwendungsbereich',
    'produkt_beschreibung',
    'produkt_hersteller_webseite',
    'produkt_hersteller_produkt_url',
  ],
  parameter: [
    'parameter_masse',
    'parameter_farbe',
    'parameter_hauptmaterial',
    'parameter_oberflaeche',
    'parameter_gewicht_pro_einheit',
    'parameter_feuerwiderstand',
    'parameter_waermeleitfaehigkeit',
    'parameter_u_wert',
    'parameter_schalldaemmung',
    'parameter_wasserbestaendigkeit',
    'parameter_dampfdiffusion',
    'parameter_einbauart',
    'parameter_wartung',
    'parameter_umweltzertifikat',
  ],
  dokumente: [
    'dokumente_datenblatt',
    'dokumente_technisches_merkblatt',
    'dokumente_produktkatalog',
    'dokumente_weitere_dokumente',
    'dokumente_bim_cad_technische_zeichnungen',
  ],
  haendler: [
    'haendler_haendlername',
    'haendler_haendler_webseite',
    'haendler_haendler_produkt_url',
    'haendler_verfuegbarkeit',
    'haendler_einheit',
    'haendler_preis',
    'haendler_preis_pro_einheit',
  ],
  erfahrung: [
    'erfahrung_einsatz_in_projekt',
    'erfahrung_muster_bestellt',
    'erfahrung_muster_abgelegt',
    'erfahrung_bewertung',
    'erfahrung_bemerkungen_notizen',
  ],
  erfassung: [
    'erfassung_quell_url',
    'erfassung_erfassungsdatum',
    'erfassung_erfassung_fuer',
    'erfassung_extraktions_log',
  ],
};
