export const SPALTEN_FELDER = {
  produkt: [
    'kategorie',
    'hersteller',
    'name_modell',
    'produktlinie_serie',
    'code_id',
    'anwendungsbereich',
    'beschreibung',
    'hersteller_webseite',
    'hersteller_produkt_url',
  ],
  parameter: [
    'masse',
    'farbe',
    'hauptmaterial',
    'oberflaeche',
    'gewicht_pro_einheit',
    'feuerwiderstand',
    'waermeleitfaehigkeit',
    'u_wert',
    'schalldaemmung',
    'wasserbestaendigkeit',
    'dampfdiffusion',
    'einbauart',
    'wartung',
    'umweltzertifikat',
  ],
  dokumente: [
    'datenblatt',
    'technisches_merkblatt',
    'produktkatalog',
    'weitere_dokumente',
    'bim_cad_technische_zeichnungen',
  ],
  haendler: [
    'haendlername',
    'haendler_webseite',
    'haendler_produkt_url',
    'verfuegbarkeit',
    'einheit',
    'preis',
    'preis_pro_einheit',
  ],
  erfahrung: [
    'einsatz_in_projekt',
    'muster_bestellt',
    'muster_abgelegt',
    'bewertung',
    'bemerkungen_notizen',
  ],
  erfassung: [
    'quell_url',
    'erfassungsdatum',
    'erfassung_fuer',
    'extraktions_log',
  ],
};
